### PR TITLE
Windows: fixes for implicit declaration of functions

### PR DESCRIPTION
**Pull request by jeroen**
This fixes two compiler warnings on mingw-w64:

```c
mongoc/mongoc-socket.c: In function 'mongoc_socket_close':
mongoc/mongoc-socket.c:774:4: warning: implicit declaration of function 'getpid' [-Wimplicit-function-declaration]
    owned = (sock->pid == (int) getpid ());
    ^
```

This PR switched to `_getpid()` on Windows (which is already used elsewhere in the code).

```c
mongoc/mongoc-util.c -o mongoc/mongoc-util.o
mongoc/mongoc-util.c: In function '_mongoc_rand_simple':
mongoc/mongoc-util.c:33:4: warning: implicit declaration of function 'rand_s' [-Wimplicit-function-declaration]
    err = rand_s (&ret);
    ^
```

The [windows documentation](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/rand-s) says:

> The `rand_s` function requires that constant `_CRT_RAND_S` be defined prior to the inclusion statement for the function to be declared.

I confirmed that this fixes the compiler warning.

### CODE REVIEW

**Comment by ajdavis** [comment]
Thanks! The getpid fix looks clearly correct to me.

In CMakeLists.txt we set the _CRT_RAND_S flag with a command line switch:
```
if (MINGW)
   # Define _CRT_RAND_S, so that MinGW's stdlib.h declares Microsoft's rand_s().
   message (" MinGW: define _CRT_RAND_S")
   set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_CRT_RAND_S")
endif ()
```
I forget, do you use Autotools to build libmongoc with mingw-w64, or do you use CMake?

**Comment by jeroen** [comment]
Ah okay I have manually hardcoded the config files for windows. I can add the macro to `mongo-config.h` instead; I just thought it's better to have it in the file with the actual `rand_s()` code.

**Comment by jeroen** [comment]
Should I remove `_CRT_RAND_S` from the PR and pass it as a compiler flag instead?

**Comment by jeroen** [comment]
Update: added a commit that fixes type warnings in the sspi code, see [CDRIVER-2427](https://jira.mongodb.org/browse/CDRIVER-2427)

**Comment by ajdavis** [comment]
Thanks. What's your opinion, should we remove the flag from CMakeLists and define it in the source file instead? If so, go ahead and make that change here.

Sorry for vacillating.

**Comment by jeroen** [comment]
In this case I prefer to define the macro in the source rather than a compiler flag because it is not an *option*, you need this macro to enable the `rand_s()` call.

Also the macro is only needed for a single `c` file, so better not enable globally which could cause other side effects (though in this particular macro that seems unlikely).

**Comment by ajdavis** [comment]
Yeah, that sounds right to me too.

**Comment by jeroen** [comment]
Should I restore it in this PR?

**Comment by ajdavis** [comment]
Yes please, and delete the flag from CMakeLists

**Comment by jeroen** [comment]
OK done

**Comment by ajdavis** [comment]
Thanks!

**Comment by ajdavis** [comment]
Merged to master and cherry-picked into the r1.9 branch as well.

**Comment by jeroen** [comment]
Thanks. I don't see it (yet) in r1.9, can you push please?

**Comment by ajdavis** [comment]
Oh yes. Sorry about that.

**Pull request merged**
