### PR TITLE
Fix ss_family build issue on AIX

### PR DESCRIPTION
**Pull request by kaplanlior**

### CODE REVIEW

**Comment by kevinAlbs** [comment]
Thanks for the contribution!

**Comment by trex58** [comment]
This change breaks our build of v1.15.2 on AIX 6.1 .
We'd like to have a rationale/explanation about the goal of this change which does not seem required in general cases.

**Comment by kaplanlior** [comment]
@trex58 What's the build error ?

**Comment by trex58** [comment]
Build fails on AIX 6.1 with GCC 8.3.0 .

Looking at details, I think that probably kaplanlior wanted to have mongodb code compatible with AIX 4.3 . However, AIX 4.3 is dead since ages ! Support of AIX 6.1 will end at end of 2019.

[ 32%] Building C object src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-socket.c.o
cd /opt/freeware/src/packages/BUILD/mongo-c-driver-1.15.2/64bit/src/libmongoc && /opt/freeware/bin/gcc -DBSON_STATIC -DMONGOC_COMPILATION -DMONGOC_STATIC -D_BSD_SOURCE -D_DEFAULT_S
OURCE -D_GNU_SOURCE -I/opt/freeware/src/packages/BUILD/mongo-c-driver-1.15.2/64bit/src/libbson/src -I/opt/freeware/src/packages/BUILD/mongo-c-driver-1.15.2/64bit/src/libmongoc/src
-I/opt/freeware/src/packages/BUILD/mongo-c-driver-1.15.2/64bit/src/libmongoc/../../src/common  -maix64 -O2 -pthread -mcmodel=large -O2 -g -DNDEBUG   -o CMakeFiles/mongoc_static.dir
/src/mongoc/mongoc-socket.c.o   -c /opt/freeware/src/packages/BUILD/mongo-c-driver-1.15.2/64bit/src/libmongoc/src/mongoc/mongoc-socket.c
In file included from /opt/freeware/src/packages/BUILD/mongo-c-driver-1.15.2/64bit/src/libmongoc/src/mongoc/mongoc-stream.h:24,
                 from /opt/freeware/src/packages/BUILD/mongo-c-driver-1.15.2/64bit/src/libmongoc/src/mongoc/mongoc-gridfs.h:25,
                 from /opt/freeware/src/packages/BUILD/mongo-c-driver-1.15.2/64bit/src/libmongoc/src/mongoc/mongoc-client.h:30,
                 from /opt/freeware/src/packages/BUILD/mongo-c-driver-1.15.2/64bit/src/libmongoc/src/mongoc/mongoc.h:29,
                 from /opt/freeware/src/packages/BUILD/mongo-c-driver-1.15.2/64bit/src/libmongoc/src/mongoc/mongoc-counters-private.h:22,
                 from /opt/freeware/src/packages/BUILD/mongo-c-driver-1.15.2/64bit/src/libmongoc/src/mongoc/mongoc-socket.c:21:
/opt/freeware/src/packages/BUILD/mongo-c-driver-1.15.2/64bit/src/libmongoc/src/mongoc/mongoc-socket.c: In function 'mongoc_socket_accept_ex':
/opt/freeware/src/packages/BUILD/mongo-c-driver-1.15.2/64bit/src/libmongoc/src/mongoc/mongoc-socket.h:42:20: error: 'struct sockaddr_storage' has no member named '__ss_family'; did
 you mean 'ss_family'?
 # define ss_family __ss_family
                    ^~~~~~~~~~~
/opt/freeware/src/packages/BUILD/mongo-c-driver-1.15.2/64bit/src/libmongoc/src/mongoc/mongoc-socket.c:718:16: note: in expansion of macro 'ss_family'
       if (addr.ss_family == AF_INET) {
                ^~~~~~~~~
gmake[2]: *** [src/libmongoc/CMakeFiles/mongoc_static.dir/build.make:768: src/libmongoc/CMakeFiles/mongoc_static.dir/src/mongoc/mongoc-socket.c.o] Error 1
gmake[2]: Leaving directory '/opt/freeware/src/packages/BUILD/mongo-c-driver-1.15.2/64bit'


AIX 6.1 : (same on AIX 7.2)
# grep -R ss_family /usr/include/*
/usr/include/netinet/in.h:        ushort_t        __ss_family;    /* address family */
/usr/include/netinet/in.h:        sa_family_t     ss_family;      /* address family */
/usr/include/sys/socket.h:        ushort_t        __ss_family;    /* address family */
/usr/include/sys/socket.h:        sa_family_t     ss_family;    /* address family */
/usr/include/sys/socket.h:      ushort_t        __ss_family;    /* address family */
/usr/include/sys/socket.h:      sa_family_t     ss_family;      /* address family */


/usr/include/netinet/in.h  : 

#if defined(**COMPAT_43**) && !defined(_KERNEL)
struct sockaddr_storage {
        ushort_t        **__ss_family**;    /* address family */
        ...........................
};
#else
struct sockaddr_storage {
        uchar_t         __ss_len;       /* address length */
        sa_family_t     **ss_family**;      /* address family */
        ..........................
};
#endif /* COMPAT_43 */

**Comment by kevinAlbs** [comment]
Hi @trex58,
Apologies for any disruption this has caused. AIX is not a [supported or tested platform for libmongoc](http://mongoc.org/libmongoc/current/installing.html#supported-platforms). We have accepted pull requests (like this one) in efforts to better support AIX. When reviewing this PR, I referred to similar changes made ([example](https://grokbase.com/t/php/php-bugs/1411ek69kj/php-bug-bug-66381-new-ss-family-was-changed-on-aix-5-3)), gathering that the ss_family field of `sockaddr_storage` is defined as __ss_family on some versions on AIX.

Upon closer look, I think that HAVE_SA_SS_FAMILY may only defined by autotools. I don't have access to an AIX machine to test, but I believe this patch may resolve the issue by testing if __ss_family is a member in cmake scripts:
https://gist.github.com/kevinAlbs/0c8bbf040c2698d7e98a502c473aacd4

If possible, can you confirm this fixes your issue?

Thank you,
Kevin

**Comment by trex58** [comment]
Hi Kevin @kevinAlbs  ,
We are porting MongoC on AIX for about 18 months. We have few patches.
I propose that we finalize the port of last mongoc version and provide you with our patches.
We test on AIX 6.1 and higher.
We'll have a deeper look at why this ss_family patch was added.
Today, with 1.15.2 version, we have:
  Pass : 1423
  Skip :  266
  Fail :    4  (/Topology/connect_timeout/succeed, /Topology/try_once/succeed, /Topology/request_scan_on_error, /TLS/handshake_stall)
Looks quite good.
I and my colleague Étienne will look at your patch and study it.
Thanks for your help !
Tony

**Comment by EGuesnet** [comment]
Hi Kevin,
I have tested your diff, and it does not work. If I have understood what you want, you must check if `ss_family` is present, and define ``ss_family`` as ``__ss_family`` if not. Your code defines``ss_family`` as ``__ss_family`` if ``__ss_family`` is **not** present.
```
#if defined(_AIX) && !defined(MONGOC_HAVE___SS_FAMILY)
 # define ss_family __ss_family
#endif
```

I have modified your gist here : https://gist.github.com/EGuesnet/d8be69aab8062b0da4beaa8302038cb3, and I have test it on master. It compiles on AIX 6.1.
On AIX 4.3 (or AIX with 4.3 compatibility), ``ss_family`` will be not found, so the define will be activated. I cannot test this diff on AIX 4.3 because we do not have so old AIX.

Thanks,
Etienne.

**Comment by kevinAlbs** [comment]
Thank you for the fix @EGuesnet, it looks good to me. Feel free to submit a pull request with those changes. @kaplanlior I believe that patch should work with the version of AIX you are running, but if you'd like to test and confirm, let us know.

**Comment by EGuesnet** [comment]
I have created the pull request (https://github.com/mongodb/mongo-c-driver/pull/592).
Thanks.

**Comment by kaplanlior** [comment]
> Thank you for the fix @EGuesnet, it looks good to me. Feel free to submit a pull request with those changes. @kaplanlior I believe that patch should work with the version of AIX you are running, but if you'd like to test and confirm, let us know.

I don't have access to such machine anymore... otherwise I would have been happy to test.

**Pull request merged**
