### PR TITLE
Resolves CDRIVER-809.

### PR DESCRIPTION
**Pull request by mschoenlaub**
This PR adds functions to programatically configure connection pool size.

### CODE REVIEW

**Comment by bjori** [comment]
Looks good, thanks!
I think we should merge this before 1.2.0-beta1.

Are you planning on updating the symbol files (see "[adding a new symbol](https://github.com/mongodb/mongo-c-driver/blob/master/CONTRIBUTING.md#adding-a-new-symbol)" in CONTRIBUTING.md)?

**Comment by mschoenlaub** [comment]
Symbol files and documentation updated. The generated manpages look fine. 
Not quite sure about my  changes to versions.ldscript though.

**Comment by bjori** [comment]
Thanks!
I'm surprised there are no new symbols yet in 1.2, I'll have a look a the versions.ldscript file.
Hopefully can merge this for 1.2 before the end of the weekend! :)

**Comment by ajdavis** [comment]
There are new symbols, you can see them sorted by libmongoc version in
versions.ldscript. In libmongoc.symbols and libmongoc.def they're not
sorted by libmongoc version, they're simply in one big list alphabetized.

On Wed, Aug 26, 2015 at 10:45 AM, Hannes Magnusson <notifications@github.com

**Comment by bjori** [comment]
@ajdavis right, looking at this PR, there are no 1.2 symbols and the new mongoc_client_pool_max_size & mongoc_client_pool_min_size are therefore added to the 1.1 section.

I realized after the comment that this is against master, not 1.2, which explains the lack of 1.2 symbols :)

**Comment by mschoenlaub** [comment]
It was quite easy to merge these commits into to 1.2.0-dev branch and moving the two new symbols in the 1.2 section of version.ldscript.
I could open another PR based on 1.2.0-dev branch, if that's the way to go. 

Are there any plans to merge this branch into master anytime soon? 
Because I would have some  ideas, depending on 45cb98a160e17cbec4bb7a5a31a46722a87641e6

**Comment by bjori** [comment]
No, master is 1.1.x, which we are not merging more fixes into (other then very very bad issues).

We've started the 1.2.0 release cycle (with beta0 already out), which is from the 1.2.0-dev branch.

1.2.0-dev will be merged into master once we release 1.2.0-stable.

I plan on merging this into 1.2.0-dev by the end of today.

**Comment by bjori** [comment]
https://github.com/mongodb/mongo-c-driver/commit/81518878e84212c07f46cdd64897462e698441f0
https://github.com/mongodb/mongo-c-driver/commit/248ff0100173fe97629c8b0dc3d3c2569c298e17
https://github.com/mongodb/mongo-c-driver/commit/b59b6381ff186ff03c742b4ac4dac4c52f048e00

I amended the commits to include the issue reference, along with fixing --enable-tracing build and the moved the symbols to the correct section in versions.ldscript

Thanks for the fix!

**Pull request closed without merging**
