### PR TITLE
edits .gitmodules, fixes libbson url

### PR DESCRIPTION
**Pull request by rubicks**
was getting socket error timeouts on `git submodule update --init` within `autogen.sh`, this change makes it work as intended.

### CODE REVIEW

**Comment by ajdavis** [comment]
Interesting. You may be behind a proxy or firewall that blocks the git protocol but allows HTTPS. Does `git clone git://github.com/mongodb/libbson.git` in a separate directory work for you, or does that time out also?

**Comment by rubicks** [comment]
Here's what that looks like for me:

    $ git clone git://github.com/mongodb/libbson.git
    Cloning into 'libbson'...
    fatal: unable to connect to github.com:
    github.com[0: 192.30.252.128]: errno=Operation timed out

I think we're agreed: my employer's firewall is probably to blame. Would my edit break anything for other people?

**Comment by ajdavis** [comment]
Thanks! @rozza pointed out to me that Github recommends HTTPS:

https://help.github.com/articles/which-remote-url-should-i-use/#cloning-with-https-recommended

**Comment by rubicks** [comment]
Sweet! Thanks @ajdavis

**Pull request merged**
