### PR TITLE
CDRIVER-886: fix wrong HTML docs configure flag

### PR DESCRIPTION
**Pull request by ksuarz**
It's `--enable-html-docs`.

### CODE REVIEW

**Comment by bjori** [comment]
mucho excelente !

**Comment by bjori** [comment]
Wait - the commit message is wrong. The ticket ID is CDRIVER-886

**Comment by ksuarz** [comment]
Oops. Fixed!

**Comment by ksuarz** [comment]
I can also rename the branch if you'd like, unless you can fix the branch name in the merge commit comment.

**Comment by bjori** [comment]
Merged in https://github.com/mongodb/mongo-c-driver/pull/277

**Pull request closed without merging**
