### PR TITLE
Fix mongoc_collection_insert_many's signature

### PR DESCRIPTION
**Pull request by NotSpooky**
Missing * for documents parameter.

### CODE REVIEW

**Comment by ajdavis** [comment]
Thanks!

**Comment by ajdavis** [comment]
I'm curious, what are you using the C Driver for?

**Comment by NotSpooky** [comment]
I'm making a Mongo library for the D language

**Comment by ajdavis** [comment]
Cool! Is it mondo, or something new?

**Comment by NotSpooky** [comment]
Something new. Was using mondo but it has a bug that I don't know how to fix.
Will be public (but incomplete) soon.

**Pull request merged**
