### PR TITLE
CDRIVER-584: Add back sockettimeoutms support

### PR DESCRIPTION
**Pull request by bjori**

### CODE REVIEW

**Comment by bjori** [comment]
@ajdavis @hanumantmk could you have a look a this and merge it if all ok?

**Comment by hanumantmk** [comment]
Happy to take it, but it doesn't do all the plumbing.  Let me try to plug all the holes

**Comment by hanumantmk** [comment]
Actually, scratch that.  We're missing threading some of the SDAM timeouts, but that isn't sockettimeoutms anywawy

**Comment by hanumantmk** [comment]
closed in 1.2.0-dev

**Pull request closed without merging**
