### PR TITLE
CDRIVER-611: Consistent treatment of integer URI options

### PR DESCRIPTION
**Pull request by bjori**
We now consitently allow =0 to mean "whatever the default value is"

### CODE REVIEW

**Comment by bjori** [comment]
@ajdavis You OK with this? :)

**Comment by ajdavis** [comment]
It's weird, but if there's a precedent then I suppose it should be consistent. Could you also look over the docs and make sure it's super-clear to people that the C Driver considers 0 equal to 300,000, at least as far as sockettimeoutms is concerned? Otherwise people might think that normal arithmetic works in our universe....

**Comment by bjori** [comment]
Merged in https://github.com/mongodb/mongo-c-driver/commit/94c4091ab040d21af9c92e224b81cd87fbb70f54

Also documented the new *MS values since I was there.

**Comment by ajdavis** [comment]
Beautiful, thank you!

**Pull request closed without merging**
